language: node_js

node_js:
  - 0.10

env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/angular-router-build/logs
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987

install:
  - mkdir -p $LOGS_DIR
  - ./scripts/sauce_connect_setup.sh
  - npm install
  - npm install -g gulp
  - npm install -g karma-cli
  - ./scripts/wait_for_browser_provider.sh

script:
  - gulp build
  - gulp templates
  - karma start --single-run --browsers SL_Chrome --reporters dots
  - ./scripts/run_protractor_tests.sh

after_script:
